source "https://github.com/CocoaPods/Old-Specs"
source 'git@bitbucket.org:dev-ennova/ios-podspecs.git'

platform :ios, '8.0'

use_frameworks!

pod 'AFNetworking', '~> 2.0'
pod 'AFURLConnectionByteSpeedMeasure'
pod 'libextobjc'
pod 'SDWebImage'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
